# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Common\Model\Customer: bcrypt
        Common\Model\Merchant: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [customer_db, merchant_db,product_db,product_photo_db,product_description_db,product_detail_list_db,category_db,brand_db]
        customer_db:
            entity: { class: Common\Model\Customer, property: email }
        merchant_db:
            entity: { class: Common\Model\Merchant, property: email }
        product_db:
             entity: { class: Common\Model\Product}
        product_photo_db:
             entity: { class: Common\Model\Product_Photo}
        product_description_db:
             entity: { class: Common\Model\Product_Description}
        product_detail_list_db:
             entity: { class: Common\Model\Product_Detail_List}
        category_db:
             entity: { class: Common\Model\Category}
        brand_db:
             entity: { class: Common\Model\Brand}     
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
      
                
        merchant:
            anonymous: ~   
            provider: merchant_db
            pattern: ^/merchant
            form_login:
                login_path: merchant_login
                check_path: merchant_login
                username_parameter: email
                password_parameter: password
                always_use_default_target_path: true
                default_target_path: merchant_index
            logout:
                path:   merchant_logout
                target: merchant_login
                
        customer:
#            remember_me: 
#                secret:   '%secret%'
#                lifetime: 604800 # 1 week in seconds
#                path:     ^/customer
            anonymous: ~  
            pattern: ^/customer
            provider: customer_db
            form_login:
                login_path: login
                check_path: login
                username_parameter: email
                password_parameter: password
                always_use_default_target_path: true
                default_target_path: index_page
                remember_me: true
            logout:
                path:   logout
                target: login        
              
        main:
            anonymous: ~  
            pattern: ^/
            
    access_control:
            - { path: ^/customer, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: ^/merchant, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: ^/customer/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: ^/merchant/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: ^/customer/index, roles: ROLE_CUSTOMER }
            - { path: ^/merchant/index, roles: ROLE_MERCHANT }
           
           