# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Common\Model\Customer: bcrypt
        Common\Model\Merchant: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [customer_db, merchant_db]
        customer_db:
            entity: { class: Common\Model\Customer, property: email }
        merchant_db:
            entity: { class: Common\Model\Merchant, property: email }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~            
            provider: customer_db
            form_login:
                login_path: login
                check_path: login
                username_parameter: email
                password_parameter: password
                always_use_default_target_path: true
                default_target_path: index_page
            logout:
                path:   logout
                target: login
                
        merchant: 
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /   
            provider: merchant_db
            form_login:
                login_path: merchant_login
                check_path: merchant_login
                username_parameter: email
                password_parameter: password
                always_use_default_target_path: true
                default_target_path: merchant_index
            logout:
                path:   merchant_logout
                target: merchant_login
                               
                