# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # acl:
    #     connection: default

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    encoders:
        Common\Model\Customer: bcrypt
        Common\Model\Merchant: bcrypt
        FOS\UserBundle\Model\UserInterface: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        chain_provider:
            chain:
                providers: [customer_db, merchant_db,product_db,product_photo_db,product_description_db,product_detail_list_db,category_db,brand_db]
        customer_db:
            entity: { class: Common\Model\Customer, property: email }
        merchant_db:
            entity: { class: Common\Model\Merchant, property: email }
        product_db:
             entity: { class: Common\Model\Product}
        product_photo_db:
             entity: { class: Common\Model\Product_Photo}
        product_description_db:
             entity: { class: Common\Model\Product_Description}
        product_detail_list_db:
             entity: { class: Common\Model\Product_Detail_List}
        category_db:
             entity: { class: Common\Model\Category}
        brand_db:
             entity: { class: Common\Model\Brand}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
      
                
        merchant:
            anonymous: ~   
            provider: merchant_db
            pattern: ^/merchant
            form_login:
                login_path: merchant_login
                check_path: merchant_login
                username_parameter: email
                password_parameter: password
                always_use_default_target_path: true
                default_target_path: merchant_index
            logout:
                path:   merchant_logout
                target: merchant_login
                
        customer:
#            remember_me: 
#                secret:   '%secret%'
#                lifetime: 604800 # 1 week in seconds
#                path:     ^/customer
            anonymous: ~  
            pattern: ^/customer
            provider: customer_db
            form_login:
                login_path: login
                check_path: login
                username_parameter: email
                password_parameter: password
                always_use_default_target_path: true
                default_target_path: index_page
                remember_me: true
            logout:
                path:   logout

                target: login       

        # -> custom firewall for the admin area of the URL
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
                target:         /admin/login
            anonymous:          true

        # -> end custom configuration

        # default login area for standard users

        # This firewall is used to handle the public login area
        # This part is handled by the FOS User Bundle

        main:
            pattern:             .*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:             true
            anonymous:          true
            
    access_control:
#            - { path: ^/customer, roles: [ROLE_CUSTOMER,IS_AUTHENTICATED_FULLY,IS_AUTHENTICATED_REMEMBERED] }
#            - { path: ^/merchant, roles: [ROLE_MERCHANT,IS_AUTHENTICATED_REMEMBERED] }
#           

             # Admin login page needs to be accessed without credential
            - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

            # Secured part of the site
            # This config requires being logged for the whole site and having the admin role for the admin part.
            # Change these rules to adapt them to your needs
            - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
            - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }